baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-relearn'
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "assets"
  
defaultContentLanguage = 'vi'

[author]
  email = 'luongtiendung.work@gmail.com'
  name = 'Dzung Luong'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en'
    languageName = 'English'
    title = 'My Website'
    weight = 1

  [languages.vi]
    contentDir = 'content/vi'
    languageCode = 'vi'
    languageName = 'Vietnamese'
    title = 'AWS Fashion Pipeline'
    weight = 2

[params]
  linkTitle = 'Amazon Web Service'
  disableLandingPageButton = true
  showVisitedLinks = true
  themeVariant = "my-branding"
  hideAuthorDate = true
  custom_css = ["css/custom.css"]
  collapsibleMenu = true

